(() => {
  const style = document.createElement('style');
  style.textContent = `
    .pickup-card .pickup-symbol{position:relative;width:min(230px,88%);aspect-ratio:.716/1;margin:20px auto 22px;border-radius:12px;overflow:hidden;background:#0a0e14;border:1px solid #3a4655;box-shadow:0 16px 38px rgba(0,0,0,.4);display:block}.pickup-card .pickup-symbol img{display:block;width:100%;height:100%;object-fit:contain;cursor:zoom-in}
    .pickup-card .pickup-info .pickup-details{margin-top:12px;padding:12px;border:1px solid var(--line);border-radius:10px;background:rgba(255,255,255,.025);text-align:left;font-size:.78rem;line-height:1.65;color:var(--muted)}.pickup-details .detail-row{margin:0 0 6px}.pickup-details .detail-row:last-child{margin-bottom:0}.pickup-details strong{color:var(--text);font-size:.72rem;margin-right:5px}.pickup-details .detail-text{white-space:pre-line}.pickup-card .pickup-detail-link{display:inline-flex;margin-top:10px;padding:8px 12px;border:1px solid var(--accent);border-radius:8px;color:var(--text);font-weight:800;font-size:.72rem;text-decoration:none;background:rgba(255,255,255,.03)}
    .pickup-card .pickup-symbol.is-loading::after{content:'日本語版画像を読み込み中…';position:absolute;inset:0;display:grid;place-items:center;color:#fff;background:rgba(10,14,20,.72)}.pickup-card .pickup-symbol.is-fallback{font-size:1rem;color:#fff;display:grid;place-items:center;text-align:center}.pickup-card .pickup-symbol.is-fallback::after{content:'カード画像を取得できませんでした'}
    .pickup-image-modal{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(0,0,0,.86);opacity:0;visibility:hidden;transition:.18s;cursor:zoom-out}.pickup-image-modal.is-open{opacity:1;visibility:visible}.pickup-image-modal img{max-width:min(92vw,560px);max-height:92vh;border-radius:14px}.pickup-image-modal-close{position:fixed;top:18px;right:22px;width:44px;height:44px;border:0;border-radius:50%;background:rgba(255,255,255,.14);color:#fff;font-size:28px;cursor:pointer}body.pickup-modal-open{overflow:hidden}
  `;document.head.appendChild(style);
  const modal=document.createElement('div');modal.className='pickup-image-modal';modal.innerHTML='<button class="pickup-image-modal-close" type="button" aria-label="閉じる">×</button><img alt="">';document.body.appendChild(modal);const modalImage=modal.querySelector('img');const close=()=>{modal.classList.remove('is-open');document.body.classList.remove('pickup-modal-open');modalImage.removeAttribute('src')};modal.addEventListener('click',e=>{if(e.target===modal)close()});modal.querySelector('button').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  const fetchJson=async url=>{const r=await fetch(url,{headers:{Accept:'application/json;q=0.9,*/*;q=0.8'},cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()};
  const getCardData=async englishName=>{const q=encodeURIComponent(englishName);const urls=[`https://api.scryfall.com/cards/search?q=${encodeURIComponent('!'+englishName+' lang:ja')}&unique=prints&order=released`,`https://api.scryfall.com/cards/named?exact=${q}`];for(const url of urls){try{const d=await fetchJson(url);const c=d.data?.[0]||d;if(c&&(c.image_uris||c.card_faces?.[0]?.image_uris))return c}catch(_){}}throw Error('card data unavailable')};
  const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const renderDetails=(card,data)=>{const info=card.querySelector('.pickup-info');if(!info)return;let box=info.querySelector('.pickup-details');if(!box){box=document.createElement('div');box.className='pickup-details';info.appendChild(box)}const face=data.card_faces?.[0]||data;const mana=face.mana_cost||'—';const type=face.printed_type_line||face.type_line||'—';const effect=face.printed_text||data.printed_text||face.oracle_text||data.oracle_text||'カード効果を取得できませんでした。';box.innerHTML=`<div class="detail-row"><strong>コスト</strong>${escapeHtml(mana)}</div><div class="detail-row"><strong>タイプ</strong>${escapeHtml(type)}</div><div class="detail-row"><strong>効果</strong><span class="detail-text">${escapeHtml(effect)}</span></div>`;const old=info.querySelector('.pickup-detail-link');if(old)old.remove();if(data.scryfall_uri){const a=document.createElement('a');a.className='pickup-detail-link';a.href=data.scryfall_uri;a.target='_blank';a.rel='noopener noreferrer';a.textContent='カード詳細を見る →';info.appendChild(a)}};
  const loadImage=url=>new Promise((res,rej)=>{const i=new Image();i.referrerPolicy='no-referrer';i.onload=()=>res(i);i.onerror=()=>rej(Error('image'));i.src=url});
  const loadCard=async card=>{const name=card.querySelector('.pickup-info h3')?.textContent?.trim();const en=card.dataset.pickupEnglishName||'';const target=card.querySelector('.pickup-symbol');if(!name||!en||!target||name==='読み込み中…')return;target.classList.add('is-loading');try{const data=await getCardData(en);const url=data.image_uris?.normal||data.image_uris?.large||data.card_faces?.[0]?.image_uris?.normal||data.card_faces?.[0]?.image_uris?.large;const img=await loadImage(url);img.alt=`${name}の日本語版カード画像`;img.loading='lazy';img.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();modalImage.src=url;modalImage.alt=`${name}のカード画像（拡大）`;modal.classList.add('is-open');document.body.classList.add('pickup-modal-open')});target.textContent='';target.appendChild(img);target.classList.remove('is-loading');renderDetails(card,data)}catch(e){console.warn('[MAGSTA] pickup card error',name,e);target.classList.remove('is-loading');target.classList.add('is-fallback')}};
  const loadAll=()=>document.querySelectorAll('.pickup-card').forEach(loadCard);document.addEventListener('magsta:daily-pickup',()=>requestAnimationFrame(loadAll),{once:true});if([...document.querySelectorAll('.pickup-card h3')].some(e=>e.textContent.trim()!=='読み込み中…'))loadAll();
})();
